/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminUI;

import clientUI.ClientDashboard;
import clientUI.MyData;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import lab_archivos_.Login;
import lab_archivos_.User;

/**
 *
 * @author graba
 */
public class AdminDashboard extends javax.swing.JFrame {

    private int mouseX;
    private int mouseY;
    private final String username;

    /**
     * Creates new form adminDashboard
     */
    public AdminDashboard(String u) {
        initComponents();
        setTitle("ShibaVet");
        setBackground(new Color(1.0f, 1.0f, 1.0f, 0f));
        jLabel4.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel4.setText(u);
        jLabel5.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel5.setText("¡Bienvenido, " + u + "!");
        jLabel7.setHorizontalAlignment(SwingConstants.CENTER);
        this.username = u;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        misDatosBtn = new javax.swing.JLabel();
        citasBtn = new javax.swing.JLabel();
        facturacionBtn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shibavet");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/lab_archivos_/img/icon.png")));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        misDatosBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        misDatosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                misDatosBtnMouseClicked(evt);
            }
        });
        getContentPane().add(misDatosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 200, 200));

        citasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        citasBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                citasBtnMouseClicked(evt);
            }
        });
        getContentPane().add(citasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 296, 190, 190));

        facturacionBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        facturacionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facturacionBtnMouseClicked(evt);
            }
        });
        getContentPane().add(facturacionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 200, 200));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 55)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("¡Bienvenido, usuario!");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 800, 61));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("usuario");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 310, 50));

        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 50, 60));

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 40, 50));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Software licenciado a: Perros PET");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 800, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab_archivos_/img/dashboard-admin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(null, "Seguro que desea cerrar sesión?");
        if (opt == 0) {
            this.setVisible(false);
            Login login = new Login();
            login.setVisible(true);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(null, "Seguro que desea salir?");
        if (opt == 0) {
            this.dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        this.setLocation(evt.getXOnScreen() - mouseX, evt.getYOnScreen() - mouseY);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MousePressed

    private void facturacionBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facturacionBtnMouseClicked
        // TODO add your handling code here:
        //facturacion btn
        Checkout ticket = new Checkout();
        ticket.setVisible(true);
    }//GEN-LAST:event_facturacionBtnMouseClicked

    private void citasBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_citasBtnMouseClicked
        try {
            // TODO add your handling code here:
            new AdminServices().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(AdminDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_citasBtnMouseClicked

    private void misDatosBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_misDatosBtnMouseClicked
        // TODO add your handling code here:
        try {
            //mis datos button
            MyData dataWindow = new MyData(User.getUserID(this.username));
            dataWindow.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(ClientDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_misDatosBtnMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel citasBtn;
    private javax.swing.JLabel facturacionBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel misDatosBtn;
    // End of variables declaration//GEN-END:variables
}
